//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologiesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.Forum_DTL = new HashSet<Forum_DTL>();
        }
    
        public int qnid { get; set; }
        public int usrid { get; set; }
        public string title { get; set; }
        public string dscrp { get; set; }
    
        public virtual ICollection<Forum_DTL> Forum_DTL { get; set; }
        public virtual User User { get; set; }
    }
}
