//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologiesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum_DTL
    {
        public int frmid { get; set; }
        public int usrid { get; set; }
        public string reply { get; set; }
        public string accepted { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual User User { get; set; }
    }
}
