//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologiesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Fora = new HashSet<Forum>();
            this.Forum_DTL = new HashSet<Forum_DTL>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string uname { get; set; }
        public string oauth { get; set; }
        public string gender { get; set; }
        public string imgpath { get; set; }
    
        public virtual ICollection<Forum> Fora { get; set; }
        public virtual ICollection<Forum_DTL> Forum_DTL { get; set; }
    }
}
